version: 2.1

orbs:
  node: circleci/node@5.1.0
  win: circleci/windows@5.0.0

commands:
  install:
    steps:
      - run: git config --global core.autocrlf input
      - node/install:
          node-version: '18.4.0'
      - run: nvm use 18.4.0
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
jobs:
  win-build:
    parameters:
      arch:
        type: enum
        enum: [ 'x64', 'arm64', 'ia32' ]
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - install
      - run: npx yarn run publisher --arch=<< parameters.arch >> --dry-run
      - store_artifacts:
          path: out
      - persist_to_workspace:
          root: .
          paths:
            - out
  publish-to-github:
    docker:
      - image: cimg/base:stable
    steps:
      - install
      - attach_workspace:
          at: .
      - run: yarn run publisher --from-dry-run
workflows:
  build:
    jobs:
      - win-build:
          matrix:
            parameters:
              arch: [ x64, ia32 ]
      - publish-to-github:
          context: storyline-release
          requires:
            - win-build-ia32
            - win-build-x64